#!/usr/bin/env python


import subprocess


ALERT_COLOR = '#FF0000'
NORMAL_COLOR = '#FFFFFF'
WARN_COLOR = '#FFCC00'

ALERT_THRESHOLD = 15
WARN_THRESHOLD = 30

acpi = [
    'acpi',
    '-b',
]
proc = subprocess.run(acpi, stdout=subprocess.PIPE)
output = proc.stdout.decode('utf-8').split('\n')[0]
info = output.split(' ')[2:5]

usage = {}
usage['status'] = info[0].rstrip(',')
usage['rate'] = info[1].rstrip(',')
usage['remain'] = ':'.join(info[2].split(':')[:2])

rate = int(usage['rate'].replace('%', ''))
if rate <= ALERT_THRESHOLD:
    color = ALERT_COLOR
elif ALERT_THRESHOLD < rate <= WARN_THRESHOLD:
    color = WARN_COLOR
else:
    color = NORMAL_COLOR

if usage['status'] == 'Charging':
    status = ''
elif usage['status'] == 'Discharging':
    status = ''
else:
    status = ''

output = ' {} ({}) {}'.format(usage['rate'], usage['remain'], status)

print(output)  # full text
print(output)  # short text
print(color)
