#!/usr/bin/env python

import os


NORMAL_COLOR = '#CCCCCC'


def to_giga(num: float) -> int:
    return int(num / 1024 / 1024 / 1024)


target = os.getenv('BLOCK_INSTANCE', '/')
stat = os.statvfs(target)

total = to_giga(stat.f_frsize * stat.f_blocks)
free = to_giga(stat.f_frsize * stat.f_bavail)
used = to_giga(stat.f_frsize * (stat.f_blocks - stat.f_bfree))

output = '<span foreground="{}"> {}G / {}G ({}G free)</span>'
print(output.format(NORMAL_COLOR, used, total, free))
