# Emacs キーバインドと衝突しても問題ないキーを prefix にする
unbind C-b
set -g prefix C-x
bind C-x send-prefix

# Alacritty で tmux を利用する
set -g default-terminal "tmux-256color"
set -as terminal-features ",alacritty:RGB"

# マウススクロールや範囲選択を可能にする
set -g mouse on

# 履歴保持は Alacritty にあわせる
set -g history-limit 100000

# バックスペースのもたつきを無くす
set -g escape-time 0

# 可能な限り Emacs キーバインドを利用する
set -g mode-keys emacs

# コピーモードに入った時点で範囲選択状態にする
bind "'" copy-mode \; send-keys -X begin-selection

# 設定再読み込みもキーバインドから可能にしておく
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded"

# セッション操作
# 操作頻度が一番低いため Meta キーバインドにしておく
bind M-c new-session
bind M-f choose-tree -w
bind M-k confirm-before -p "kill-session #S? (y/n)" kill-session

# ウインドウ操作
# 操作頻度が中程度なので単独キーとバインドしておく
bind k confirm-before -p "kill-window #W? (y/n)" kill-window

# ペイン操作
# 操作頻度が最も高いので prefix キーからそのまま操作できるようにしておく
bind C-v split-window -v -c "#{pane_current_path}"
bind C-h split-window -h -c "#{pane_current_path}"
bind C-n select-pane -t :.+
bind C-p select-pane -t :.-
bind C-o display-panes

# ペインステータスと被らないよう、ステータスラインは上部に表示する
set -g status-position top

# セッション情報はステータスラインの左端に表示する
# tmux のキー入力待ちかどうかも視覚的に判別できるようにする
set -g status-left ""
set -g status-right "#[fg=#{@thm_crust},bg=#{?client_prefix,#{E:@thm_peach},#{E:@thm_teal}},bold] session: #S #[fg=default,bg=default]"
set -g status-right-length 100

# catppuccin テーマを利用する
set -g @catppuccin_flavor "mocha"
set -g @catppuccin_pane_border_status "top"
set -g @catppuccin_pane_status_enabled "yes"
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_flags "icon"
set -g @catppuccin_status_background "#{@thm_surface_0}"

# catppuccin テーマの有効化
# mkdir -p ~/.config/tmux/plugins/catppuccin
# git clone -b v2.3.0 https://github.com/catppuccin/tmux.git ~/.config/tmux/plugins/catppuccin/tmux
run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# アクティブペインはペイン情報を表示させて判断する
# ボーダーでの判断は分かりにくいため、すべてのペインで同色にしておく
set -wg pane-border-format "#{?pane_active,#[fg=#{@thm_surface_0}]#[bg=#{@thm_lavender}] #{pane_index} #[fg=#{@thm_lavender}]#[bg=#{@thm_surface_0}] #{b:pane_current_path} #[fg=default]#[bg=default],}"
set -g pane-active-border-style "fg=#{@thm_overlay_0}"
set -g pane-border-lines "single"
set -g pane-border-status "bottom"

# コピー範囲を視認しやすいカラーに変更しておく
set -g mode-style "bg=#{@thm_peach},fg=#{@thm_crust}"

# プラグインマネージャーを有効化
# paru -S tmux-plugin-manager
run /usr/share/tmux-plugin-manager/tpm
