Parameter settings:
    AccelFactor             = 0.268097
    BottomEdge              = 450
    CircularPad             = 1
    CircularScrolling       = 1
    ClickPad                = 0
    EmulateTwoFingerMinW    = 7
    EmulateTwoFingerMinZ    = 282
    FingerHigh              = 20
    FingerLow               = 15
    GrabEventDevice         = 0
    HorizHysteresis         = 3
    HorizScrollDelta        = 14
    HorizTwoFingerScroll    = 1
    LeftEdge                = 80
    MaxSpeed                = 1.75
    MaxTapMove              = 32
    MinSpeed                = 1
    PalmMinWidth            = 10
    PalmMinZ                = 200
    PressureMotionMaxZ      = 160
    PressureMotionMinZ      = 30
    RightEdge               = 450
    TapButton1              = 1
    TapButton2              = 3
    TapButton3              = 2
    TopEdge                 = 80
    VertEdgeScroll          = 0
    VertScrollDelta         = 14
    VertTwoFingerScroll     = 1
    VertHysteresis          = 3
