add_newline = false
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$package\
$elm\
$nodejs\
$python\
$rust\
$cmd_duration\
$line_break\
$character"""
scan_timeout = 30

[aws]
disabled = true

[battery]
disabled = true

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[✖](bold red)"

[cmd_duration]
min_time = 2_000
show_milliseconds = true
style = "bold yellow"

[conda]
disabled = true

[crystal]
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 8

[dotnet]
disabled = true

[env_var]
disabled = true

[git_branch]
symbol = "🌱 "

[git_state]
disabled = true

[git_status]
deleted.style = "red"
modified.style = "blue"
renamed.style = "yellow"
staged.style = "green"
style = "bright-black"
untracked.style = "yellow"

[golang]
disabled = true

[java]
disabled = true

[nix_shell]
disabled = true

[php]
disabled = true

[python]
pyenv_version_name = true

[ruby]
disabled = true

[terraform]
disabled = true

[username]
show_always = true
style_root = "bold red"
style_user = "bold purple"
