[global/wm]
include-file = ~/src/github.com/catppuccin/polybar/themes/mocha.ini

[bar/main]
background = ${colors.mantle}
enable-ipc = true
font-0 = "UDEV Gothic NF:pixelsize=14;3"
font-1 = "UDEV Gothic NF:style=Bold:pixelsize=14;3"
height = 32
locale = ja_JP.UTF-8
padding-left = 1
padding-right = 1
separator = |
separator-foreground = ${colors.surface1}
wm-restack = generic

module-margin = 1
modules-left = date xworkspaces
modules-right = cpu memory filesystem network battery tray

[settings]
# 画面構成変更時に polybar を再起動させる
screenchange-reload = true

[module/battery]
type = internal/battery

adapter = AC
battery = BAT1
full-at = 99
low-at = 10
poll-interval = 10
time-format = %H:%M

# 充電中
label-charging = "󰂄  %percentage%%"
label-charging-foreground = ${colors.blue}
label-charing-padding = 1

# バッテリーで稼動中
label-discharging = "󱧥  %percentage%% (%time%)"
label-discharging-foreground = ${colors.overlay0}

# 満充電
label-full = "󱟢  Fully Charged"
label-full-foreground = ${colors.green}

# バッテリー残量・少
label-low = "󰂃  %percentage% (%time%)"
label-low-foreground = ${colors.yellow}

[module/cpu]
type = internal/cpu

interval = 1
warn-percentage = 90

label = "   %percentage%%"
label-foreground = ${colors.overlay0}
label-padding = 1
label-warn-foreground = ${colors.yellow}

[module/date]
type = internal/date

date = %Y/%m/%d(%a)
interval = 3
time = %H:%M:%S

label = "󰃰  %date% %time%"
label-foreground = ${colors.overlay0}
label-padding-right = 1

[module/filesystem]
type = internal/fs

interval = 10
mount-0 = /
warn-percentage = 80

label-mounted = "   %used% / %total%"
label-mounted-foreground = ${colors.overlay0}
label-mounted-padding = 1
label-warn-foreground = ${colors.yellow}

[module/memory]
type = internal/memory

interval = 3
warn-percentage = 80

label = "   %gb_used% / %gb_total%"
label-foreground = ${colors.overlay0}
label-padding = 1
labe-warn-foreground = ${colors.yellow}

[module/network]
type = custom/script

exec = ~/.config/polybar/network.sh
interval = 5

label-foreground = ${colors.overlay0}
label-padding = 1

[module/tray]
type = internal/tray

tray-background = ${colors.mantle}
tray-maxsize = 24
tray-padding = 8

[module/xworkspaces]
type = internal/xworkspaces
pin-workspaces = false
show-urgent = true

# アクティブワークスペース
label-active = %name%
label-active-background = ${colors.maroon}
label-active-foreground = ${colors.mantle}
label-active-padding = 1

# 利用していないワークスペースは表示しない
label-empty =

# 非アクティブワークスペース
label-occupied = %name%
label-occupied-foreground = ${colors.overlay0}
label-occupied-padding = 1

# アプリケーションから通知が来たワークスペース
label-urgent = %name%
label-urgent-background = ${colors.yellow}
label-urgent-foreground = ${colors.mantle}
