;; Ruby settings
(when (require 'ruby-mode nil t)
  (defun my-ruby-mode-hook ()
    (add-to-list 'auto-mode-alist '("\\.rb$" . ruby-mode))
    (add-to-list 'auto-mode-alist '("Capfile$" . ruby-mode))
    (add-to-list 'auto-mode-alist '("Gemfile$" . ruby-mode))
    (setq ruby-deep-indent-paren-style nil)
    (define-key ruby-mode-map (kbd "=") (smartchr '(" = " " == " "=")))
    (define-key ruby-mode-map (kbd "!") (smartchr '("!" " != ")))
    (define-key ruby-mode-map (kbd "|") (smartchr '("|`!!'|" "|")))
    (define-key ruby-mode-map (kbd "{") (smartchr '("{`!!'}" "{")))
    (define-key ruby-mode-map (kbd ">") (smartchr '(" > " " => " " -> " ">")))
    (define-key ruby-mode-map [return] 'reindent-then-newline-and-indent))
  (add-hook 'ruby-mode-hook 'my-ruby-mode-hook))

(when (require 'ruby-end nil t)
  (abbrev-mode 1)
  (electric-pair-mode t)
  (electric-indent-mode t)
  (electric-layout-mode t))

(when (require 'ruby-block nil t)
  (ruby-block-mode t)
  (setq ruby-block-highlight-toggle t))
