(when (require 'rust-mode nil t)
  (setq racer-cmd "/home/taro/.multirust/toolchains/nightly/cargo/bin/racer")
  (setq racer-rust-src-path "/usr/local/src/rustc-nightly/src")
  (define-key rust-mode-map (kbd "=") (smartchr '(" = " " == " "=")))
  (define-key rust-mode-map (kbd "+") (smartchr '(" + " "+" " += ")))
  (define-key rust-mode-map (kbd "-") (smartchr '(" - " "-" " -= ")))
  (define-key rust-mode-map (kbd "!") (smartchr '("!" " != ")))
  (define-key rust-mode-map (kbd ">") (smartchr '(">" " > " " -> " " => " " >= ")))
  (define-key rust-mode-map (kbd "<") (smartchr '("<`!!'>" "<" " < " " <- " " <= ")))
  (define-key rust-mode-map (kbd "|") (smartchr '("|`!!'|" "||" "|")))

  (add-hook 'rust-mode-hook #'racer-mode)
  (add-hook 'racer-mode-hook #'eldoc-mode)
  (add-hook 'racer-mode-hook #'company-mode)
  (local-set-key (kbd "C-i") #'company-indent-or-complete-common)
  (setq company-tooltip-align-annotations t))
