(when (require 'rust-mode nil t)
  (define-key rust-mode-map (kbd "=") (smartchr '(" = " " == " "=")))
  (define-key rust-mode-map (kbd "+") (smartchr '(" + " "+" " += ")))
  (define-key rust-mode-map (kbd "-") (smartchr '(" - " "-" " -= ")))
  (define-key rust-mode-map (kbd "!") (smartchr '("!" " != ")))
  (define-key rust-mode-map (kbd ">") (smartchr '(">" " > " " -> " " => " " >= ")))
  (define-key rust-mode-map (kbd "<") (smartchr '("<`!!'>" "<" " < " " <- " " <= ")))
  (define-key rust-mode-map (kbd "|") (smartchr '("|`!!'|" "||" " | " "|")))

  (setq racer-rust-src-path "/home/taro/.racer-src/rustc-1.10.0/src/")
  (add-hook 'rust-mode-hook 'cargo-minor-mode)
  (add-hook 'rust-mode-hook 'rust-enable-format-on-save)
  (add-hook 'rust-mode-hook #'racer-mode)
  (add-hook 'racer-mode-hook #'eldoc-mode)
  (add-hook 'racer-mode-hook #'company-mode)
  (local-set-key (kbd "C-i") #'company-indent-or-complete-common)
  (setq company-tooltip-align-annotations t))
