;; PHP settings
(autoload 'php-mode "php-mode")
(setq auto-mode-alist
      (cons '("\\.php\\'" . php-mode) auto-mode-alist))
(setq php-mode-force-pear nil)
(setq c-auto-newline nil)
(add-hook 'php-mode-hook
          '(lambda ()
             (require 'php-completion)
             (php-completion-mode nil)
             (define-key php-mode-map (kbd "C-o") 'phpcmp-complete)
             (when (require 'auto-complete nil t)
               (make-variable-buffer-local 'ac-sources)
               (add-to-list 'ac-sources 'ac-source-php-completion)
               (auto-complete-mode t))
             (c-set-style "python")
             (c-set-offset 'case-label 4)
             (c-set-offset 'arglist-intro 4)
             (c-set-offset 'arglist-con-nonempty 4)
             (c-set-offset 'arglist-close 0)
             (setq indent-tabs-mode nil)
             (setq c-basic-offset 4)
             (define-key php-mode-map (kbd "=") (smartchr '(" = " " === " "=" " == ")))
             (define-key php-mode-map (kbd ">") (smartchr '(">" "->" "=>" " >>> ")))
             (define-key php-mode-map (kbd "!") (smartchr '("!" " !== " " != ")))))

