;; JavaScript settings
(when (require 'js2-mode nil t)
  (add-to-list 'auto-mode-alist '("\\.js$" . js2-mode))
  (defun my-js2-mode-hook ()
    (setq js2-basic-offset 2)
    (define-key js2-mode-map (kbd "=") (smartchr '(" = " " === " "=" " == ")))
    (define-key js2-mode-map (kbd "!") (smartchr '("!" " !== " " != ")))
    (define-key js2-mode-map (kbd "+") (smartchr '("+" "++" " += ")))
    (define-key js2-mode-map (kbd "-") (smartchr '("-" "--" " -= ")))
    (define-key js2-mode-map (kbd "<") (smartchr '("<" " < " " <= ")))
    (define-key js2-mode-map (kbd ">") (smartchr '(">" " > " " >= "))))
  (add-hook 'js2-mode-hook 'my-js2-mode-hook))
