;; Python settings
(when (require 'python-mode nil t)
  (defun my-python-mode-hook ()
    (setq auto-mode-alist (cons '("\\.py$" . python-mode) auto-mode-alist))
    (setq interpreter-mode-alist (cons '("python" . python-mode)
                                       interpreter-mode-alist))
    (autoload 'python-mode "python-mode" "Python editing mode." t)
    (setq py-indent-offset 4)
    (setq tab-width py-indent-offset)
    (define-key python-mode-map (kbd "\"") (smartchr '("\"`!!'\"" "\"" "\"\"\"`!!'\"\"\"")))
    (define-key python-mode-map (kbd "\'") (smartchr '("'`!!''" "'" "'''`!!''''")))
    (define-key python-mode-map (kbd "=") (smartchr '(" = " " == " "=")))
    (define-key python-mode-map (kbd "!") (smartchr '("!" " != ")))
    (define-key python-mode-map (kbd "-") (smartchr '("-" " -= ")))
    (define-key python-mode-map (kbd "+") (smartchr '("+" " += "))))
  (add-hook 'python-mode-hook 'my-python-mode-hook))
